version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/api/src
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker


  my-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'myproject1'
      MYSQL_ROOT_PASSWORD: '12345678'
    command:
      --sql_mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    ports:
      - 3306:3306

        ##STRICT_TRANS_TABLES,
